# Generated by Django 5.1.2 on 2024-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainpageinfoblock_delete_mainpageadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=128, verbose_name='Статус показа на страницах'),
        ),
    ]
