# Generated by Django 5.1.2 on 2024-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_offer_shipping_pack_alter_brand_banner_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=128, verbose_name='Статус показа на страницах'),
        ),
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='instructions', verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=128, verbose_name='Статус показа на страницах'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=128, verbose_name='Статус показа на страницах'),
        ),
    ]
