# Generated by Django 5.1.2 on 2024-10-09 08:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_brand_status_alter_category_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='C:\\Users\\amur_\\Desktop\\NDA\\NDA_app\\privateprivate/'), upload_to='instructions', verbose_name='Инструкция'),
        ),
    ]
